#MIDI Instruments

#PIANO
ACOUSTIC_GRAND_PIANO = 0
BRIGHT_ACOUSTIC_PIANO = 1
ELECTRIC_GRAND_PIANO = 2
HONKY_TONK_PIANO = 3
ELECTRIC_PIANO_1 = 4
ELECTRIC_PIANO_2 = 5
HARPSICHORD = 6
CLAVINET = 7
#Chromatic Percussion
CELESTA = 8
GLOCKENSPIEL = 9
MUSIC_BOX = 10
VIBRAPHONE = 11
MARIMBA = 12
XYLOPHONE = 13
TUBULAR_BELLS = 14
DULCIMER = 15
#Organ
ELECTRIC_GUITAR_CLEAN = 27
DISTORTION_GUITAR = 30
